version: '3.8'

services:
  app:
    build:
      context: .  # Build from the Dockerfile in the current directory
    container_name: mvom-system
    ports:
      - "4000:4000"  # Expose Express app to localhost
    environment:
      - PORT=${PORT}
      - DB_URL=${DB_URL}
      - JWT_CUSTOMER_SECRET=${JWT_CUSTOMER_SECRET}
      - JWT_VENDOR_SECRET=${JWT_VENDOR_SECRET}
      - JWT_ADMIN_SECRET=${JWT_ADMIN_SECRET}
    networks:
      - app-network

# Volumes to persist MongoDB data
volumes:
  mongodb-data:

# Networks to allow containers to communicate
networks:
  app-network:
    driver: bridge
